version: '3.8'

services:
  frontend:
    build: ./frontend/tourio
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend/tourio
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./backend/tourio:/app
